colchonet/config/routes.rb
Rails.application.routes.draw do
    LOCALES = /en|pt\-BR/

    scope ":locale", :locale => LOCALES do
        resources :rooms
        resources :users

        resource :confirmation, :only=> [:show]
    end

    get '/:locale' => 'home#index', :locale => LOCALES
    root 'home#index'
end

colchonet/app/models/room.rb
class Room < ApplicationRecord

    validates_presence_of :title, :location, :description

    def complete_name
        "#{title}, #{location}"
    end
end

colchonet/app/models/user.rb
class User < ApplicationRecord
    validates_presence_of :email, :full_name, :location
    validates_length_of :bio, minimum: 30, allow_blank: false
    validates_format_of :email, with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/, on: :create
    validates_uniqueness_of :email

    has_secure_password

    before_create :generate_token

    def generate_token
        self.confirmation_token = SecureRandom.urlsafe_base64
    end

    def confirm!
        return if confirmed?

        self.confirmed_at = Time.current
        self.confirmation_token = ''
        save!
    end

    def confirmed?
        confirmed_at.present?
    end
end

colchonet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action do
        I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options
        { :locale => I18n.locale }
    end
end

colchonet/app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController

    def show
        user = User.find_by_confirmation_token(params[:token])
        if user.present?
            user.confirm!
            redirect_to user,
            :notice => I18n.t('users.confirmations.success')
        else
            redirect_to root_path
        end
    end
    
end

colchonet/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @rooms = Room.limit(3)
    end
end

colchonet/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

colchonet/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            SignupMailer.confirm_email(@user).deliver
            redirect_to @user, :notice => 'Cadastro criado com sucesso!'
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        puts @user.valid?
        if @user.update(user_params)
            redirect_to @user, :notice => 'Cadastro atualizado com sucesso!'
        else
            render :edit
        end
    end

    private
    def user_params
        params.require(:user).permit(:full_name, :location, :email, :password, :password_confirmation, :bio)
    end
end

colchonet/app/helpers/application_helper.rb
module ApplicationHelper

    def error_tag(model, attribute)
        if model.errors.has_key? attribute
            content_tag :div, model.errors[attribute].first,
            :class => 'error_message'
        end
    end

end

colchonet/app/helpers/rooms_helper.rb
module RoomsHelper
end

colchonet/app/views/home/index.html.erb
<h1>Quartos recém postados</h1>

<ul>
    <% @rooms.each do |room| %>
        <li><%= link_to room.complete_name, room %></li>
    <% end %>
</ul>

colchonet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colchonet</title>
    <link href='http://fonts.googleapis.com/css?family=Pac' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>

  </head>
  <body>
      <header>
          <div id="header-wrap">
              <h1><%= link_to "colcho.net", root_path %> </h1>
              <nav>
                  <ul>
                      <li><%= link_to t('layout.rooms'), rooms_path %> </li>
                      <li><%= link_to t('layout.signup'), new_user_path %> </li>
                  </ul>
              </nav>
          </div>
      </header>

      <div id="content">
          <% if notice.present? %>
              <p id="notice"><%= notice %> </p>
          <% end %>
          <% if alert.present? %>
              <p id="alert"><%= alert %> </p>
          <% end %>

          <%= yield %>
      </div>
  </body>
</html>

colchonet/app/views/rooms/_form.html.erb
<% if @room.errors.any? %>
    <div id="error_explanation">
        Há erros no formulário, por favor verifique.
    </div>
<% end %>

<%= form_for @room do |f| %>
    <p>
        <%= f.label :title %> <br />
        <%= f.text_field :title %>
        <%= error_tag @room, :title %>
    </p>

    <p>
        <%= f.label :location %> <br />
        <%= f.text_field :location %>
        <%= error_tag @room, :location %>
    </p>

    <p>
        <%= f.label :description %> <br />
        <%= f.text_field :description %>
        <%= error_tag @room, :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

colchonet/app/views/rooms/edit.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form', room: @room %>
<%= link_to t('links.show'), @room %> |
<%= link_to t('links.back'), rooms_path %>

colchonet/app/views/rooms/index.html.erb
<h1><%= t '.title' %></h1>

<table>
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.room.title' %></th>
      <th><%= t 'activerecord.attributes.room.location' %></th>
      <th><%= t 'activerecord.attributes.room.description' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= room.location %></td>
        <td><%= room.description %></td>
        <td><%= link_to t('links.show'), room %></td>
        <td><%= link_to t('links.edit'), edit_room_path(room) %></td>
        <td><%= link_to t('links.destroy'), room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new'), new_room_path %>

colchonet/app/views/rooms/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form', room: @room %>
<%= link_to t('links.back'), rooms_path %>

colchonet/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>